// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package models

import (
	"database/sql"
)

type Hub struct {
	ID         string       `db:"id" json:"id"`
	Name       string       `db:"name" json:"name"`
	LocationID string       `db:"location_id" json:"location_id"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type Team struct {
	ID         string       `db:"id" json:"id"`
	Name       string       `db:"name" json:"name"`
	Type       string       `db:"type" json:"type"`
	HubID      string       `db:"hub_id" json:"hub_id"`
	LocationID string       `db:"location_id" json:"location_id"`
	CreatedAt  sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID        string       `db:"id" json:"id"`
	Name      string       `db:"name" json:"name"`
	Type      string       `db:"type" json:"type"`
	TeamID    string       `db:"team_id" json:"team_id"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}
