// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package models

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateHub(ctx context.Context, arg CreateHubParams) (*Hub, error)
	DeleteHub(ctx context.Context, id string) (*Hub, error)
	FindHubByID(ctx context.Context, id string) (*Hub, error)
	GetListHub(ctx context.Context, arg GetListHubParams) ([]*Hub, error)
	SearchHub(ctx context.Context, dollar_1 sql.NullString) ([]*Hub, error)
	UpdateHub(ctx context.Context, arg UpdateHubParams) (*Hub, error)
}

var _ Querier = (*Queries)(nil)
